### PR TITLE
Observe ActiveRecord conventions

### PR DESCRIPTION
**Pull request by ivanoblomov**
Patches for #59 and #66.

Note snippet in #66 to override the default key.

### CODE REVIEW

**Comment by dankohn** [comment]
@jashmenn We would love to get your feedback on this PR.

**Comment by jashmenn** [comment]
Hmm yeah, we added it that way because it matched the MySQL `HEX` function (https://github.com/jashmenn/activeuuid/commit/4e418f4c6ba321ef85a10fb52594aae3b22567a6) but I can see why you'd want it to return the string UUID. 

It's tricky, this is a breaking change and we might need a major version increment. Can you speak more to why we want to do it this way? I haven't worked closely with this code in a while and I want to be careful about breaking existing users' code. Does anyone else want to weigh in? /cc @pyromaniac  ?

**Comment by dankohn** [comment]
The context is that we had our whole app working with UUID ids with Postgres, and then needed to switch to MySQL because of changing requirements. The built-in Rails support for UUID ids in Postgres returns UUIDs (not the MySQL HEX output), and so it seems that activeuuid should as well.

Among other things, I would hope that this gem might eventually get accepted into Rails core.

But, I certainly agree that you would want to rev the version number.

**Comment by jashmenn** [comment]
Ah - got it. Also, my main concern is ensuring that we're able to use uuids as conveniently as regular ids. Can you confirm for me that this pull req doesn't break the finders? It seems like it should work, but I haven't had a chance to try it out.

**Comment by dankohn** [comment]
Yes, finders work just as we expect.

**Comment by jashmenn** [comment]
Okay great, I'll merge this - we'll have to bump the major version for the next release. Thanks!!

**Comment by dankohn** [comment]
Thanks!

--
Dan Kohn <mailto:dan@dankohn.com>
tel:+1-415-233-1000

**Pull request merged**
